### ISSUE TITLE
Readme colors only color codes

### ISSUE THREAD

**Issue by p3h3** [StoneLabs/AVR-Programmer#1]
Main readme under the supported and tested section is displayed as:
#32CD32 Supported and tested
#FFA500 Supported not tested
instead of the actual colors yellow/orange and green.

**Comment by StoneLabs** [comment]
Huh, it seems that the certificate for via.placeholder.com expired on 12/26/2020.
I'll wait a couple of days to see if it gets fixed. If not I will put the images inside the repository.

**Comment by StoneLabs** [comment]
Fixed.
